module.exports.supportedCurrencies = [
    { name : "Bitcoin" , id : 1 },
    { name : "Ethereum" , id : 1027 },
    { name : "Tether" , id : 825 },
    { name : "BNB" , id : 1839 },
    { name : "USD Coin" , id : 3408 },
    { name : "XRP" , id : 52 },
    { name : "Binance USD" , id : 4687 },
    { name : "Cardano" , id : 2010 },
    { name : "Dogecoin" , id : 74 },
    { name : "Polygon" , id : 3890 },
    { name : "Solana" , id : 5426 },
    { name : "Polkadot" , id : 6636 },
    { name : "Litecoin" , id : 2 },
    { name : "Avalanche" , id : 5805 },
    { name : "Shiba Inu" , id : 5994 },
    { name : "Dai" , id : 4943 },
    { name : "TRON" , id : 1958 },
    { name : "Uniswap" , id : 7083 },
    { name : "Wrapped Bitcoin" , id : 3717 },
    { name : "Cosmos" , id : 3794 },
    { name : "Chainlink" , id : 1975 },
    { name : "UNUS SED LEO" , id : 3957 },
    { name : "Monero" , id : 328 },
    { name : "Ethereum Classic" , id : 1321 },
    { name : "Toncoin" , id : 11419 },
    { name : "Aptos" , id : 21794 },
    { name : "Bitcoin Cash" , id : 1831 },
    { name : "Stellar" , id : 512 },
    { name : "OKB" , id : 3897 },
    { name : "ApeCoin" , id : 18876 },
    { name : "NEAR Protocol" , id : 6535 },
    { name : "Cronos" , id : 3635 },
    { name : "Filecoin" , id : 2280 },
    { name : "Lido DAO" , id : 8000 },
    { name : "Algorand" , id : 4030 },
    { name : "Quant" , id : 3155 },
    { name : "VeChain" , id : 3077 },
    { name : "Internet Computer" , id : 8916 },
    { name : "Hedera" , id : 4642 },
    { name : "Decentraland" , id : 1966 },
    { name : "Fantom" , id : 3513 },
    { name : "Aave" , id : 7278 },
    { name : "EOS" , id : 1765 },
    { name : "BitDAO" , id : 11221 },
    { name : "Axie Infinity" , id : 6783 },
    { name : "The Sandbox" , id : 6210 },
    { name : "MultiversX" , id : 6892 },
    { name : "Flow" , id : 4558 },
    { name : "Theta Network" , id : 2416 },
    { name : "Terra Classic" , id : 4172 }
]